name: Release

on:
  push:
    tags:
      - 'v*.*.*'  # Laukaisee version tageista, kuten v1.0.0

jobs:
  release:
    name: Release with JReleaser
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Set up GPG
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | base64 --decode > private.key
          gpg --batch --import private.key
        env:
          GPG_TTY: ${{ secrets.GPG_TTY }}

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Set up JReleaser
        uses: jreleaser/release-action@v2
        with:
          version: latest
        env:
          JRELEASER_PROJECT_VERSION: ${{ github.ref_name }}

      - name: Run JReleaser full-release
        run: jreleaser full-release --git-root-search
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_SIGNING_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          JRELEASER_SIGNING_PASSWORD: ${{ secrets.GPG_PASSPHRASE }}
          JRELEASER_DEPLOY_MAVEN_MAVENCENTRAL_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          JRELEASER_DEPLOY_MAVEN_MAVENCENTRAL_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
